---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: wiki
spec:
  encryptedData:
    .dockerconfigjson: AgCfnUedkGjzcbUIHwEnCgE/1ZF8SZtSS5RDvc++vhKBcfRagtMKQSv3eFOj3fY/QHvflWkErOsiYo32zfzt8X27Kkk243jBbzzbzfNHuwnU4tkjl9dkLxS4Ao5yzRkuJwblP1Aq9QCFkkMTFVkLTxVNCIKulGYpEPbYuJm8XqsoOHCN68Q0xhz0J3mYx2asPzoHCz47f7MEBDUah/SPI+T0oBC+QCyLCR8VdZ2VrJG2KGAgk+BX+czJrQQsOeTah34x9NWnoMRbxf9MaPhb/EGTQMw1pWRLI2gzscwrV3UIjXa0F8ynvXfqQ7E/NJIELk0Tf6YabVB5LU14zOJ9kAnds9vUKPj5Iiimc48pBxrnA0i2U384jLDsjOVrHdExIY8RSPhyLo002NE96vNLEFLJbuDxT0c0QCniPBWtq6Zv0Q6h2hssal6eAPH22SzNMYI1N/1qrNImU6A5PDHe7sZNN9nLYEgQj68EEF/piU4w2+86zzI2heQvfkGe2eGoBY+GhFt1svU4NC71N6XB3k5tNTMJebofRiaJfx9Wfql8xTtTTD7CGCkdjkBK8Gep0qReplvxoD93bRMXnFP7+oyjntsp23KcwDzG8lNfeF4iKk+3534XWAR3GVP76Uu/AYdjaf7subpuNAJFtABTNlJ2lIrWVNIjGKzPbG7EI+KDDIUUv5r9ordxvers5FI2/D1wNVqRE0xd3cJ0HirbVBj+dhP9Mt4Ezvy1Bx/MUnjOE7M6gWszjru7IJ35j7dgvHcL/ZrnRtfozaSch44jh5avsTA8rp/DZjicJ/sWX7DqF9umJNw/Sulovho9daWIz9P8BFLxwxh6d45DKlHyfL+o4gaUPArtbHrA9QQh9YZsxTeldQ2AoJLxx8V6G11dQMI4/TFWXifK+gvQNHpU3XLvkxU82xXh859tmGQ=
  template:
    metadata:
      name: ghcr-secret
      namespace: wiki
    type: kubernetes.io/dockerconfigjson
